# Generated by Django 4.0.4 on 2022-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0002_alter_enterprise_user_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacant',
            old_name='state',
            new_name='status',
        ),
        migrations.AddField(
            model_name='networking',
            name='state',
            field=models.CharField(blank=True, choices=[('ghosting', 'Ghosting'), ('information', 'Information'), ('well_comunication', 'Well Comunication')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='mail',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
