# Generated by Django 4.0.4 on 2022-05-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web', models.URLField(blank=True, null=True)),
                ('glassdoor_link', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('technical', 'Technical'), ('cultural', 'Cultural')], max_length=100, null=True)),
                ('preparation', models.TextField(blank=True)),
                ('feed_back', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('cancelled', 'Cancelled'), ('not_approved', 'Not Approved'), ('next_interview', 'Next Interview'), ('ghosting', 'Ghosting')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('my_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('feed_back', models.TextField(blank=True)),
                ('roll', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacante', to='traker.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='NetWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_interviewer', models.BooleanField(default=False)),
                ('enterprise_opinion', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('feed_back', models.TextField(blank=True)),
                ('position', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='traker.enterprise')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='traker.interview')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='vacant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='traker.vacant'),
        ),
    ]
