# Generated by Django 4.0.4 on 2022-06-02 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('glassdoor_link', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_social', models.URLField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('status_in', models.CharField(blank=True, choices=[('ghosting', 'Ghosting'), ('information', 'Information'), ('well_comunication', 'Well Comunication')], max_length=100, null=True)),
                ('enterprise_opinion', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('feed_back', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_Name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('send_cv', 'Send Cv'), ('ghosting', 'Ghosting'), ('next_interview', 'Next Interview'), ('not_approved', 'Not Approved')], max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('roll_description', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('enterprise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacante', to='traker.enterprise')),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('tlf', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='traker.networking')),
            ],
        ),
        migrations.AddField(
            model_name='networking',
            name='vacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='traker.vacant'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('technical', 'Technical'), ('cultural', 'Cultural')], max_length=100, null=True)),
                ('preparation', models.TextField(blank=True)),
                ('feed_back', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
                ('vacant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='traker.vacant')),
            ],
        ),
    ]
