# Generated by Django 4.0.4 on 2022-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='networking',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vacant',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
