# Generated by Django 4.0.4 on 2022-05-31 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networking',
            old_name='status',
            new_name='status_in',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='user_register',
        ),
        migrations.RemoveField(
            model_name='networking',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='vacant',
            name='feed_back',
        ),
        migrations.RemoveField(
            model_name='vacant',
            name='my_cv',
        ),
        migrations.AddField(
            model_name='networking',
            name='main_social',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networking',
            name='vacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='traker.vacant'),
        ),
        migrations.AlterField(
            model_name='vacant',
            name='enterprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacante', to='traker.enterprise'),
        ),
        migrations.DeleteModel(
            name='SocialNetworks',
        ),
    ]
