# Generated by Django 4.0.4 on 2022-06-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0002_rename_status_networking_status_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
