# Generated by Django 4.0.4 on 2022-05-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0003_rename_state_vacant_status_networking_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networking',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='vacant',
            name='status',
            field=models.CharField(blank=True, choices=[('send_cv', 'Send Cv'), ('ghosting', 'Ghosting'), ('next_interview', 'Next Interview'), ('not_approved', 'Not Approved')], max_length=100, null=True),
        ),
    ]
