# Generated by Django 4.0.4 on 2022-05-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0004_rename_state_networking_status_alter_vacant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networking',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='networking',
            name='is_interviewer',
        ),
        migrations.AddField(
            model_name='networking',
            name='social_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='traker.socialnetworks'),
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networking',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
