# Generated by Django 4.0.4 on 2022-05-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0006_alter_networking_social_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networking',
            name='social_network',
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='traker.networking'),
        ),
    ]
