# Generated by Django 4.0.4 on 2022-05-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0007_remove_networking_social_network_socialnetworks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
