# Generated by Django 4.0.4 on 2022-05-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traker', '0008_alter_socialnetworks_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='tlf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
